import os
from io import BytesIO
from datetime import datetime
from typing import Any, List

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

def register_devanagari_fonts(base_dir: str):
    regular = os.path.join(base_dir, "assets", "fonts", "NotoSansDevanagari-Regular.ttf")
    bold = os.path.join(base_dir, "assets", "fonts", "NotoSansDevanagari-Bold.ttf")

    if not os.path.exists(regular):
        return # Cannot register

    if "NotoDeva" not in pdfmetrics.getRegisteredFontNames():
        pdfmetrics.registerFont(TTFont("NotoDeva", regular))

    if os.path.exists(bold) and "NotoDeva-Bold" not in pdfmetrics.getRegisteredFontNames():
        pdfmetrics.registerFont(TTFont("NotoDeva-Bold", bold))

def translate_labels(lang: str) -> dict:
    if lang == "hi":
        return {
            "patient_name": "रोगी का नाम",
            "report_id": "रिपोर्ट आईडी",
            "age": "आयु",
            "sex": "लिंग",
            "generated_at": "तैयार किया गया",
            "output_language": "आउटपुट भाषा",
            "confidence": "विश्वास स्तर",
            "model_used": "मॉडल उपयोग किया",
            "overall": "Overall Summary",
            "findings": "Key Findings",
            "abnormal": "Abnormal Values Explained",
            "next": "Next Steps",
            "urgent": "Urgent Warning Signs",
            "glossary": "Glossary (Difficult Terms)",
            "disclaimer": "Disclaimer",
        }
    if lang == "mr":
        return {
            "patient_name": "रुग्णाचे नाव",
            "report_id": "रिपोर्ट आयडी",
            "age": "वय",
            "sex": "लिंग",
            "generated_at": "तयार केले",
            "output_language": "आउटपुट भाषा",
            "confidence": "विश्वास स्तर",
            "model_used": "मॉडेल वापरले",
            "overall": "Overall Summary",
            "findings": "Key Findings",
            "abnormal": "Abnormal Values Explained",
            "next": "Next Steps",
            "urgent": "Urgent Warning Signs",
            "glossary": "Glossary (Difficult Terms)",
            "disclaimer": "Disclaimer",
        }
    return {
        "patient_name": "Patient Name",
        "report_id": "Report ID",
        "age": "Age",
        "sex": "Sex",
        "generated_at": "Generated At",
        "output_language": "Output Language",
        "confidence": "Confidence",
        "model_used": "Model Used",
        "overall": "Overall Summary",
        "findings": "Key Findings",
        "abnormal": "Abnormal Values Explained",
        "next": "Next Steps",
        "urgent": "Urgent Warning Signs",
        "glossary": "Glossary (Difficult Terms)",
        "disclaimer": "Disclaimer",
    }

def _pdf_header_footer(canvas, doc, footer_text: str, font_name="Helvetica", font_bold="Helvetica-Bold"):
    canvas.saveState()
    width, height = A4

    canvas.setFont(font_bold, 11)
    canvas.drawString(40, height - 40, "MediBrief — Patient-Friendly Medical Summary")

    canvas.setFont(font_name, 9)
    canvas.drawString(40, height - 55, "Generated by AI (for informational use only)")

    canvas.setStrokeColorRGB(0.7, 0.7, 0.7)
    canvas.line(40, height - 62, width - 40, height - 62)

    canvas.setStrokeColorRGB(0.7, 0.7, 0.7)
    canvas.line(40, 45, width - 40, 45)

    canvas.setFont(font_name, 8)
    canvas.drawString(40, 30, footer_text[:120])
    canvas.drawRightString(width - 40, 30, f"Page {canvas.getPageNumber()}")

    canvas.restoreState()

def build_summary_pdf_bytes(
    result: dict,
    patient_name: str,
    patient_age: str,
    patient_sex: str,
    report_id: str,
    project_root: str
) -> bytes:
    buffer = BytesIO()
    meta = result.get("meta", {})
    req_lang = meta.get("requested_language", "en")

    if req_lang in ["hi", "mr"]:
        register_devanagari_fonts(project_root)
        if "NotoDeva" in pdfmetrics.getRegisteredFontNames():
            FONT = "NotoDeva"
            FONT_BOLD = "NotoDeva-Bold" if "NotoDeva-Bold" in pdfmetrics.getRegisteredFontNames() else "NotoDeva"
        else:
            FONT = "Helvetica"
            FONT_BOLD = "Helvetica-Bold"
    else:
        FONT = "Helvetica"
        FONT_BOLD = "Helvetica-Bold"

    labels = translate_labels(req_lang)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="Cell", fontSize=9, leading=11, fontName=FONT))
    styles.add(ParagraphStyle(name="CellBold", fontSize=9, leading=11, fontName=FONT_BOLD))
    styles.add(ParagraphStyle(name="Small", fontSize=9, leading=11, fontName=FONT))
    styles.add(ParagraphStyle(name="Section", fontSize=12, leading=14, spaceAfter=6, spaceBefore=10, fontName=FONT_BOLD))

    generated_at = datetime.now().strftime("%d %b %Y, %I:%M %p")
    footer_text = "Not medical advice. For emergencies, seek urgent medical care."

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=40,
        rightMargin=40,
        topMargin=80,
        bottomMargin=70,
        title="MediBrief Summary",
    )

    story: List[Any] = []

    lang_line = f"{meta.get('language_name', 'not provided')} ({meta.get('requested_language', '')})"
    conf_line = meta.get("confidence", "not provided")
    model_used = meta.get("model_used", "not provided")

    p_name = patient_name.strip() if patient_name.strip() else "Not provided"
    p_age = patient_age.strip() if patient_age.strip() else "Not provided"
    p_sex = patient_sex.strip() if patient_sex.strip() else "Not provided"
    r_id = report_id.strip() if report_id.strip() else "Not provided"

    info_data = [
        [Paragraph(labels["patient_name"], styles["CellBold"]), Paragraph(p_name, styles["Cell"]),
         Paragraph(labels["report_id"], styles["CellBold"]), Paragraph(r_id, styles["Cell"])],

        [Paragraph(labels["age"], styles["CellBold"]), Paragraph(p_age, styles["Cell"]),
         Paragraph(labels["sex"], styles["CellBold"]), Paragraph(p_sex, styles["Cell"])],

        [Paragraph(labels["generated_at"], styles["CellBold"]), Paragraph(generated_at, styles["Cell"]),
         Paragraph(labels["output_language"], styles["CellBold"]), Paragraph(lang_line, styles["Cell"])],

        [Paragraph(labels["confidence"], styles["CellBold"]), Paragraph(conf_line, styles["Cell"]),
         Paragraph(labels["model_used"], styles["CellBold"]), Paragraph(model_used, styles["Cell"])],
    ]

    table = Table(info_data, colWidths=[95, 165, 85, 135])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.whitesmoke),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))

    story.append(table)
    story.append(Spacer(1, 10))

    def add_bullets(title: str, items: list):
        story.append(Paragraph(title, styles["Section"]))
        if items:
            story.append(ListFlowable(
                [ListItem(Paragraph(str(x), styles["Small"])) for x in items],
                bulletType="bullet",
                leftIndent=18
            ))
        else:
            story.append(Paragraph("Not provided.", styles["Small"]))
        story.append(Spacer(1, 8))

    add_bullets(labels["overall"], result.get("overall_summary_bullets", []))
    add_bullets(labels["findings"], result.get("key_findings", []))

    story.append(Paragraph(labels["abnormal"], styles["Section"]))
    abn = result.get("abnormal_values_explained", [])
    if abn:
        lines = []
        for row in abn:
            lines.append(
                f"{row.get('test','')}: {row.get('value','')} {row.get('unit','')} "
                f"(Range: {row.get('reference_range','not provided')}, Flag: {row.get('flag','unknown')}) "
                f"→ {row.get('meaning_simple','')}"
            )
        story.append(ListFlowable(
            [ListItem(Paragraph(x, styles["Small"])) for x in lines],
            bulletType="bullet",
            leftIndent=18
        ))
    else:
        story.append(Paragraph("No abnormal lab values found / not provided.", styles["Small"]))
    story.append(Spacer(1, 8))

    add_bullets(labels["next"], result.get("next_steps", []))
    add_bullets(labels["urgent"], result.get("urgent_warning_signs", []))

    story.append(Paragraph(labels["glossary"], styles["Section"]))
    gloss = result.get("glossary", [])
    if gloss:
        lines = [f"{g.get('term','')}: {g.get('meaning_simple','')}" for g in gloss]
        story.append(ListFlowable(
            [ListItem(Paragraph(x, styles["Small"])) for x in lines],
            bulletType="bullet",
            leftIndent=18
        ))
    else:
        story.append(Paragraph("Not provided.", styles["Small"]))

    disclaimer = result.get("disclaimer", "")
    if isinstance(disclaimer, list):
        disclaimer = " ".join(str(d) for d in disclaimer)
    
    if disclaimer:
        story.append(Spacer(1, 8))
        story.append(Paragraph(labels["disclaimer"], styles["Section"]))
        story.append(Paragraph(str(disclaimer), styles["Small"]))

    doc.build(
        story,
        onFirstPage=lambda c, d: _pdf_header_footer(c, d, footer_text, FONT, FONT_BOLD),
        onLaterPages=lambda c, d: _pdf_header_footer(c, d, footer_text, FONT, FONT_BOLD),
    )

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
